#!/bin/bash

# The pre_start_cartridge and pre_stop_cartridge hooks are *SOURCED*
# immediately before (re)starting or stopping the specified cartridge.
# They are able to make any desired environment variable changes as
# well as other adjustments to the application environment.

# The post_start_cartridge and post_stop_cartridge hooks are executed
# immediately after (re)starting or stopping the specified cartridge.

# Exercise caution when adding commands to these hooks.  They can
# prevent your application from stopping cleanly or starting at all.
# Application start and stop is subject to different timeouts
# throughout the system.

# The version of TorqueBox to install. Should be either LATEST, an
# official release (e.g. 2.1.3) or an incremental build number (e.g. 1594)
VERSION=3.0.0.beta2

if [ $(ulimit -u) -lt 500 ]; then
  ulimit -u 500
fi

# Reduce the messaging threads to conserve memory
# This also gets used for jgroups and jgroups-oob threads
export MESSAGING_THREAD_RATIO=0.10 # AS7 cart defaults to 0.2

source $OPENSHIFT_REPO_DIR/.openshift/torquebox.sh

if [ ! -f $TORQUEBOX_HOME/$VERSION ]; then
    torquebox_install $VERSION
    #db_migrate
    touch $TORQUEBOX_HOME/$VERSION
fi

bundle_install
